name: pharaoh
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - awscli=1.43.2
  - binutils_impl_linux-64=2.45
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cffi=2.0.0
  - colorama=0.4.6
  - docutils=0.18.1
  - gcc_impl_linux-64=15.2.0
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - jmespath=1.0.1
  - kernel-headers_linux-64=6.12.0
  - ld_impl_linux-64=2.45
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-devel_linux-64=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libsanitizer=15.2.0
  - libsqlite=3.51.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.2
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.0
  - pip=25.3
  - pyasn1=0.6.1
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.14.0
  - python-dateutil=2.9.0.post0
  - python_abi=3.14
  - pyyaml=6.0.3
  - readline=8.2
  - rsa=4.7.2
  - rust=1.91.1
  - rust-std-x86_64-unknown-linux-gnu=1.91.1
  - six=1.17.0
  - sysroot_linux-64=2.39
  - tk=8.6.13
  - yaml=0.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - aenum==3.1.16
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - asttokens==3.0.1
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - boto3==1.34.0
      - botocore==1.34.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - curl-cffi==0.13.0
      - decorator==5.2.1
      - deprecated==1.3.1
      - dnspython==2.8.0
      - executing==2.2.1
      - frozendict==2.4.7
      - frozenlist==1.8.0
      - future==1.0.0
      - genai==2.1.0
      - google-auth==2.43.0
      - google-genai==1.52.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - ipython==8.37.0
      - jedi==0.19.2
      - line-bot-sdk==3.21.0
      - matplotlib-inline==0.2.1
      - multidict==6.7.0
      - multitasking==0.0.12
      - numpy==2.3.5
      - openai==0.27.10
      - pandas==2.3.3
      - parso==0.8.5
      - peewee==3.18.3
      - pexpect==4.9.0
      - platformdirs==4.5.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1-modules==0.4.2
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pymongo==4.15.0
      - pymongo-auth-aws==1.3.0
      - pytz==2025.2
      - regex==2025.11.3
      - requests==2.32.3
      - s3transfer==0.9.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tiktoken==0.3.3
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.0.7
      - wcwidth==0.2.14
      - websockets==15.0.1
      - wrapt==2.0.1
      - yarl==1.22.0
      - yfinance==0.2.66
